# Generated by Django 2.0.2 on 2019-07-26 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_id', models.IntegerField(verbose_name='用户id')),
                ('content', models.CharField(max_length=140, verbose_name='内容')),
                ('types', models.IntegerField(choices=[(0, '原创'), (1, '评论'), (2, '转发')])),
                ('state', models.IntegerField(choices=[(0, '删除'), (1, '正常')])),
                ('top', models.BooleanField(default=False)),
                ('permit', models.IntegerField(choices=[(0, '删除'), (1, '正常')])),
                ('media_url', models.CharField(max_length=140, verbose_name='媒体地址')),
                ('publish_location', models.CharField(max_length=140, verbose_name='地理位置')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '内容',
                'verbose_name_plural': '内容',
            },
        ),
        migrations.CreateModel(
            name='ContentInteract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(verbose_name='内容id')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('content', models.IntegerField(verbose_name='评论数')),
                ('tran', models.BooleanField(verbose_name='转发数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '内容互动数',
                'verbose_name_plural': '内容互动数',
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(verbose_name='内容id')),
                ('tag_id', models.IntegerField(verbose_name='tag_id')),
            ],
            options={
                'verbose_name': '内容的内容标签',
                'verbose_name_plural': '内容的内容标签',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_key', models.CharField(max_length=40, verbose_name='标签的key')),
                ('tag_name', models.CharField(max_length=40, verbose_name='标签的key')),
            ],
            options={
                'verbose_name': '内容标签',
                'verbose_name_plural': '内容标签',
            },
        ),
    ]
